server {
    listen 80;
    server_name localhost;

    # DNS interno do Docker
    resolver 127.0.0.11 valid=30s;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Intercepta /api/Products e manda para o Estoque
    location ~* ^/api/Products {
        set $inventory_backend http://inventory-service:8080;
        proxy_pass $inventory_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Intercepta /api/Invoice e manda para o Faturamento
    location ~* ^/api/Invoices? {
        set $billing_backend http://billing-service:8080;
        proxy_pass $billing_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}